language: node_js
node_js:
  - "10.13.0"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
# TODO: LINTING
# - ng lint 
- ng test --watch=false
- ng build --prod