language: node_js
node_js:
  - "10.13.0"
dist: trusty
sudo: required
branches:
  only:
  - master
  - develop
before_script:
  - npm install -g @angular/cli
  - export CHROME_BIN=chromium-browser
script:
# TODO: LINTING
# - ng lint 
- ng test --watch=false
- ng build --prod